### ISSUE TITLE
AstroClip Tutorial 

### ISSUE THREAD

**Issue by julia-ve-kim** [PolymathicAI/AstroCLIP#16]
I have been frequently & recently referencing the AstroCLIP tutorial at the following link 
https://github.com/PolymathicAI/AstroCLIP/blob/main/notebooks/tutorial/AstroCLIPTutorial.ipynb
but it appears that the Tutorial has just been removed. I was wondering whether you can publish a new copy of it, for I was intending to rely & reference its code for a research project of mine at the University of Toronto.

**Comment by lsarra** [comment]
We moved the old tutorial to this branch https://github.com/PolymathicAI/AstroCLIP/blob/ai_for_science/notebooks/tutorial/AstroCLIPTutorial.ipynb
